//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale.Apps.Cards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Apps.Cards.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Downs / {1:n0} Revives.
        /// </summary>
        public static string DownsRevives {
            get {
                return ResourceManager.GetString("DownsRevives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Experience Gained.
        /// </summary>
        public static string ExperienceGained {
            get {
                return ResourceManager.GetString("ExperienceGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First played {0} (across {1:n0} sessions).
        /// </summary>
        public static string FirstSession {
            get {
                return ResourceManager.GetString("FirstSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Headshots ({1:0.0}%).
        /// </summary>
        public static string Headshots {
            get {
                return ResourceManager.GetString("Headshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Headshots.
        /// </summary>
        public static string HeadshotsCount {
            get {
                return ResourceManager.GetString("HeadshotsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} points.
        /// </summary>
        public static string Highscore {
            get {
                return ResourceManager.GetString("Highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} K/D ({1:n0} Kills / {2:n0} Deaths).
        /// </summary>
        public static string Kd {
            get {
                return ResourceManager.GetString("Kd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Kills.
        /// </summary>
        public static string KillCount {
            get {
                return ResourceManager.GetString("KillCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} KPR ({1:n0} Kills / {2:n0} Rounds).
        /// </summary>
        public static string KillsPerRound {
            get {
                return ResourceManager.GetString("KillsPerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Match {0} ({1:n0} MMR).
        /// </summary>
        public static string LastMatch {
            get {
                return ResourceManager.GetString("LastMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen {0}.
        /// </summary>
        public static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Matches Played.
        /// </summary>
        public static string MatchesPlayed {
            get {
                return ResourceManager.GetString("MatchesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Melee Kills ({1:0.0}%).
        /// </summary>
        public static string Melee {
            get {
                return ResourceManager.GetString("Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} played.
        /// </summary>
        public static string ModeTimePlayed {
            get {
                return ResourceManager.GetString("ModeTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MMR to {1} ({2}%).
        /// </summary>
        public static string NextRank {
            get {
                return ResourceManager.GetString("NextRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0}.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not played yet.
        /// </summary>
        public static string OperatorNotPlayed {
            get {
                return ResourceManager.GetString("OperatorNotPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} K/D · {1:0.00} W/L · {2}.
        /// </summary>
        public static string OperatorSummary {
            get {
                return ResourceManager.GetString("OperatorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Penetration Kills ({1:0.0}%).
        /// </summary>
        public static string Penetrations {
            get {
                return ResourceManager.GetString("Penetrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} ± {1:n0} MMR ({2}).
        /// </summary>
        public static string SeasonMmr {
            get {
                return ResourceManager.GetString("SeasonMmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} MMR ({1}).
        /// </summary>
        public static string SeasonRank {
            get {
                return ResourceManager.GetString("SeasonRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} ({1:n0} Wins / {2:n0} Losses + {2:n0} Abandons).
        /// </summary>
        public static string SeasonWl {
            get {
                return ResourceManager.GetString("SeasonWl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Suicides ({1:0.0}%).
        /// </summary>
        public static string Suicides {
            get {
                return ResourceManager.GetString("Suicides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} W/L ({1:n0} Wins / {2:n0} Losses).
        /// </summary>
        public static string Wl {
            get {
                return ResourceManager.GetString("Wl", resourceCulture);
            }
        }
    }
}
