//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperatorActions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperatorActions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Objects.OperatorActions", typeof(OperatorActions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.E.L.M.A. Detonations.
        /// </summary>
        public static string Ace {
            get {
                return ResourceManager.GetString("Ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies Tricked by Prisma.
        /// </summary>
        public static string Alibi {
            get {
                return ResourceManager.GetString("Alibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Distance Reeled.
        /// </summary>
        public static string Amaru {
            get {
                return ResourceManager.GetString("Amaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructions by Breaching Round.
        /// </summary>
        public static string Ash {
            get {
                return ResourceManager.GetString("Ash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock Wire Kills.
        /// </summary>
        public static string Bandit {
            get {
                return ResourceManager.GetString("Bandit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets Stopped by Shield.
        /// </summary>
        public static string Blackbeard {
            get {
                return ResourceManager.GetString("Blackbeard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies Blinded by Flash Shield.
        /// </summary>
        public static string Blitz {
            get {
                return ResourceManager.GetString("Blitz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills with the Skeleton Key.
        /// </summary>
        public static string Buck {
            get {
                return ResourceManager.GetString("Buck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills with Incendiary Bolts.
        /// </summary>
        public static string Capitao {
            get {
                return ResourceManager.GetString("Capitao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Panels Deployed.
        /// </summary>
        public static string Castle {
            get {
                return ResourceManager.GetString("Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Interrogations Performed.
        /// </summary>
        public static string Caveira {
            get {
                return ResourceManager.GetString("Caveira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies Killed while Slowed Down.
        /// </summary>
        public static string Clash {
            get {
                return ResourceManager.GetString("Clash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teammates Revived.
        /// </summary>
        public static string Doc {
            get {
                return ResourceManager.GetString("Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Hacks.
        /// </summary>
        public static string Dokkaebi {
            get {
                return ResourceManager.GetString("Dokkaebi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies Disoriented by Yokai.
        /// </summary>
        public static string Echo {
            get {
                return ResourceManager.GetString("Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grzmot Mines Detonated.
        /// </summary>
        public static string Ela {
            get {
                return ResourceManager.GetString("Ela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrenal Surge Bonuses.
        /// </summary>
        public static string Finka {
            get {
                return ResourceManager.GetString("Finka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies caught in Welcome Mats.
        /// </summary>
        public static string Frost {
            get {
                return ResourceManager.GetString("Frost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Charge Kills.
        /// </summary>
        public static string Fuze {
            get {
                return ResourceManager.GetString("Fuze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper Kills.
        /// </summary>
        public static string Glaz {
            get {
                return ResourceManager.GetString("Glaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcáns Detonated by Your Team.
        /// </summary>
        public static string Goyo {
            get {
                return ResourceManager.GetString("Goyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trax Stingers Deployed.
        /// </summary>
        public static string Gridlock {
            get {
                return ResourceManager.GetString("Gridlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-KAIROS Pellets Detonated.
        /// </summary>
        public static string Hibana {
            get {
                return ResourceManager.GetString("Hibana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills after using Replicator.
        /// </summary>
        public static string Iana {
            get {
                return ResourceManager.GetString("Iana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets Spotted by Electronics Detector.
        /// </summary>
        public static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyenox Tracking Assists.
        /// </summary>
        public static string Jackal {
            get {
                return ResourceManager.GetString("Jackal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets Destroyed by Active Defense.
        /// </summary>
        public static string Jäger {
            get {
                return ResourceManager.GetString("Jäger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electroclaws successfully deployed.
        /// </summary>
        public static string Kaid {
            get {
                return ResourceManager.GetString("Kaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets Destroyed with the LV.
        /// </summary>
        public static string Kali {
            get {
                return ResourceManager.GetString("Kali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Denial Device Kills.
        /// </summary>
        public static string Kapkan {
            get {
                return ResourceManager.GetString("Kapkan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies Poisoned by GU Devices.
        /// </summary>
        public static string Lesion {
            get {
                return ResourceManager.GetString("Lesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies Detected by EE-ONE-D.
        /// </summary>
        public static string Lion {
            get {
                return ResourceManager.GetString("Lion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies Killed by Evil Eye.
        /// </summary>
        public static string Maestro {
            get {
                return ResourceManager.GetString("Maestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torch Breaches.
        /// </summary>
        public static string Maverick {
            get {
                return ResourceManager.GetString("Maverick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attackers slowed by Banshee.
        /// </summary>
        public static string Melusi {
            get {
                return ResourceManager.GetString("Melusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Mirrors Deployed.
        /// </summary>
        public static string Mira {
            get {
                return ResourceManager.GetString("Mira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets Blocked by Extended Shield.
        /// </summary>
        public static string Montagne {
            get {
                return ResourceManager.GetString("Montagne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drones Hacked.
        /// </summary>
        public static string Mozzie {
            get {
                return ResourceManager.GetString("Mozzie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets Jammed.
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Tools Deceived.
        /// </summary>
        public static string Nokk {
            get {
                return ResourceManager.GetString("Nokk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airjabs Detonated.
        /// </summary>
        public static string Nomad {
            get {
                return ResourceManager.GetString("Nomad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills after Remah Dashes.
        /// </summary>
        public static string Oryx {
            get {
                return ResourceManager.GetString("Oryx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeats Spotted.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Plates Taken by Teammates.
        /// </summary>
        public static string Rook {
            get {
                return ResourceManager.GetString("Rook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items destructed by Breaching Hammer.
        /// </summary>
        public static string Sledge {
            get {
                return ResourceManager.GetString("Sledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison gas kills.
        /// </summary>
        public static string Smoke {
            get {
                return ResourceManager.GetString("Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounted LMG Kills.
        /// </summary>
        public static string Tachanka {
            get {
                return ResourceManager.GetString("Tachanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets Destroyed by EMP.
        /// </summary>
        public static string Thatcher {
            get {
                return ResourceManager.GetString("Thatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcements Breached by Exo-Thermic Charge.
        /// </summary>
        public static string Thermite {
            get {
                return ResourceManager.GetString("Thermite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets Destroyed by Shock Drone.
        /// </summary>
        public static string Twitch {
            get {
                return ResourceManager.GetString("Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Eye Cameras Deployed.
        /// </summary>
        public static string Valkyrie {
            get {
                return ResourceManager.GetString("Valkyrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drones Deceived.
        /// </summary>
        public static string Vigil {
            get {
                return ResourceManager.GetString("Vigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectiles Captured.
        /// </summary>
        public static string Wamai {
            get {
                return ResourceManager.GetString("Wamai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills While Using Glance.
        /// </summary>
        public static string Warden {
            get {
                return ResourceManager.GetString("Warden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candela Devices Detonated.
        /// </summary>
        public static string Ying {
            get {
                return ResourceManager.GetString("Ying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets Destroyed by ARGUS Camera.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concussion Grenades Detonated.
        /// </summary>
        public static string Zofia {
            get {
                return ResourceManager.GetString("Zofia", resourceCulture);
            }
        }
    }
}
