//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale.Cards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Cards.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual K/D.
        /// </summary>
        public static string CasualKd {
            get {
                return ResourceManager.GetString("CasualKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual W/L.
        /// </summary>
        public static string CasualWl {
            get {
                return ResourceManager.GetString("CasualWl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downs vs Revives.
        /// </summary>
        public static string DownsRevives {
            get {
                return ResourceManager.GetString("DownsRevives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Session.
        /// </summary>
        public static string FirstSession {
            get {
                return ResourceManager.GetString("FirstSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Rank.
        /// </summary>
        public static string HighestRank {
            get {
                return ResourceManager.GetString("HighestRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills/Round.
        /// </summary>
        public static string KillsPerRound {
            get {
                return ResourceManager.GetString("KillsPerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Match.
        /// </summary>
        public static string LastMatch {
            get {
                return ResourceManager.GetString("LastMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Rank Progress.
        /// </summary>
        public static string NextRankProgress {
            get {
                return ResourceManager.GetString("NextRankProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Ability.
        /// </summary>
        public static string OperatorAbility {
            get {
                return ResourceManager.GetString("OperatorAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator K/D.
        /// </summary>
        public static string OperatorKd {
            get {
                return ResourceManager.GetString("OperatorKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator W/L.
        /// </summary>
        public static string OperatorWl {
            get {
                return ResourceManager.GetString("OperatorWl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall K/D.
        /// </summary>
        public static string OverallKd {
            get {
                return ResourceManager.GetString("OverallKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall W/L.
        /// </summary>
        public static string OverallWl {
            get {
                return ResourceManager.GetString("OverallWl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked K/D.
        /// </summary>
        public static string RankedKd {
            get {
                return ResourceManager.GetString("RankedKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked W/L.
        /// </summary>
        public static string RankedWl {
            get {
                return ResourceManager.GetString("RankedWl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season K/D.
        /// </summary>
        public static string SeasonKd {
            get {
                return ResourceManager.GetString("SeasonKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season MMR.
        /// </summary>
        public static string SeasonMmr {
            get {
                return ResourceManager.GetString("SeasonMmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season W/L.
        /// </summary>
        public static string SeasonWl {
            get {
                return ResourceManager.GetString("SeasonWl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Played.
        /// </summary>
        public static string TimePlayed {
            get {
                return ResourceManager.GetString("TimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist Hunt K/D.
        /// </summary>
        public static string TrainingKd {
            get {
                return ResourceManager.GetString("TrainingKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist Hunt W/L.
        /// </summary>
        public static string TrainingWl {
            get {
                return ResourceManager.GetString("TrainingWl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unranked K/D.
        /// </summary>
        public static string UnrankedKd {
            get {
                return ResourceManager.GetString("UnrankedKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unranked W/L.
        /// </summary>
        public static string UnrankedWl {
            get {
                return ResourceManager.GetString("UnrankedWl", resourceCulture);
            }
        }
    }
}
