//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Core", typeof(Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barricades.
        /// </summary>
        public static string Barricades {
            get {
                return ResourceManager.GetString("Barricades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Tester.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        public static string Bomb {
            get {
                return ResourceManager.GetString("Bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Casual Deaths.
        /// </summary>
        public static string CasualDeaths {
            get {
                return ResourceManager.GetString("CasualDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual K/D.
        /// </summary>
        public static string CasualKD {
            get {
                return ResourceManager.GetString("CasualKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Casual Kills.
        /// </summary>
        public static string CasualKills {
            get {
                return ResourceManager.GetString("CasualKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Casual Losses.
        /// </summary>
        public static string CasualLosses {
            get {
                return ResourceManager.GetString("CasualLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Casual Wins.
        /// </summary>
        public static string CasualWins {
            get {
                return ResourceManager.GetString("CasualWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual W/L.
        /// </summary>
        public static string CasualWL {
            get {
                return ResourceManager.GetString("CasualWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Players.
        /// </summary>
        public static string CompareButton {
            get {
                return ResourceManager.GetString("CompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Rank.
        /// </summary>
        public static string CompareRank {
            get {
                return ResourceManager.GetString("CompareRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Region:.
        /// </summary>
        public static string CurrentRegion {
            get {
                return ResourceManager.GetString("CurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked - Current Season.
        /// </summary>
        public static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downs.
        /// </summary>
        public static string Downs {
            get {
                return ResourceManager.GetString("Downs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use the Dragon6 API to check account status, get tokens and ranked info. These may send the players iD, which is publicly avalible. Ubisoft servers are contacted directly by your computer to get the stats..
        /// </summary>
        public static string Dragon6PrivactLineTwo {
            get {
                return ResourceManager.GetString("Dragon6PrivactLineTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Privacy.
        /// </summary>
        public static string Dragon6Privacy {
            get {
                return ResourceManager.GetString("Dragon6Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Desktop is Owned and Maintained by DragonFruit Network..
        /// </summary>
        public static string Dragon6PrivacyLineOne {
            get {
                return ResourceManager.GetString("Dragon6PrivacyLineOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Official Dragon6 Team.
        /// </summary>
        public static string Dragon6TeamDescription {
            get {
                return ResourceManager.GetString("Dragon6TeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintained by DragonFruit Network.
        /// </summary>
        public static string Dragon6TeamMaintainers {
            get {
                return ResourceManager.GetString("Dragon6TeamMaintainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Team.
        /// </summary>
        public static string Dragon6TeamTitle {
            get {
                return ResourceManager.GetString("Dragon6TeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Revives.
        /// </summary>
        public static string GeneralRevives {
            get {
                return ResourceManager.GetString("GeneralRevives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshot %.
        /// </summary>
        public static string HeadshotPerc {
            get {
                return ResourceManager.GetString("HeadshotPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshots.
        /// </summary>
        public static string Headshots {
            get {
                return ResourceManager.GetString("Headshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostage.
        /// </summary>
        public static string Hostage {
            get {
                return ResourceManager.GetString("Hostage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K/D.
        /// </summary>
        public static string KD {
            get {
                return ResourceManager.GetString("KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locally Stored.
        /// </summary>
        public static string LocalStorage {
            get {
                return ResourceManager.GetString("LocalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string Losses {
            get {
                return ResourceManager.GetString("Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Rank.
        /// </summary>
        public static string MaxRank {
            get {
                return ResourceManager.GetString("MaxRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Kills.
        /// </summary>
        public static string Melee {
            get {
                return ResourceManager.GetString("Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee %.
        /// </summary>
        public static string MeleePerc {
            get {
                return ResourceManager.GetString("MeleePerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Region:.
        /// </summary>
        public static string NewRegion {
            get {
                return ResourceManager.GetString("NewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published by {0}.
        /// </summary>
        public static string NewsPublisher {
            get {
                return ResourceManager.GetString("NewsPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Six News.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official List.
        /// </summary>
        public static string OfficialList {
            get {
                return ResourceManager.GetString("OfficialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Operator Stats.
        /// </summary>
        public static string OperatorStatsButton {
            get {
                return ResourceManager.GetString("OperatorStatsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall K/D.
        /// </summary>
        public static string OverallKD {
            get {
                return ResourceManager.GetString("OverallKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall W/L.
        /// </summary>
        public static string OverallWL {
            get {
                return ResourceManager.GetString("OverallWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Ranked Deaths.
        /// </summary>
        public static string RankedDeaths {
            get {
                return ResourceManager.GetString("RankedDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked K/D.
        /// </summary>
        public static string RankedKD {
            get {
                return ResourceManager.GetString("RankedKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Ranked Kills.
        /// </summary>
        public static string RankedKills {
            get {
                return ResourceManager.GetString("RankedKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Ranked Losses.
        /// </summary>
        public static string RankedLosses {
            get {
                return ResourceManager.GetString("RankedLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Ranked Wins.
        /// </summary>
        public static string RankedWins {
            get {
                return ResourceManager.GetString("RankedWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked W/L.
        /// </summary>
        public static string RankedWL {
            get {
                return ResourceManager.GetString("RankedWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recents.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you search for a player, come back here and you&apos;ll see them in this list. We will keep the 20 most recent searches, so it doesn&apos;t get too cluttered..
        /// </summary>
        public static string RecentsDescription {
            get {
                return ResourceManager.GetString("RecentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Players you&apos;ve searched for in the past..
        /// </summary>
        public static string RecentsHeader {
            get {
                return ResourceManager.GetString("RecentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Region.
        /// </summary>
        public static string RegionChangerText {
            get {
                return ResourceManager.GetString("RegionChangerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Ranked Region: {0}.
        /// </summary>
        public static string RegionSelectorText {
            get {
                return ResourceManager.GetString("RegionSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcements.
        /// </summary>
        public static string Reinforcements {
            get {
                return ResourceManager.GetString("Reinforcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account.
        /// </summary>
        public static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revives.
        /// </summary>
        public static string Revives {
            get {
                return ResourceManager.GetString("Revives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Accounts (Beta).
        /// </summary>
        public static string SavedAccountsText {
            get {
                return ResourceManager.GetString("SavedAccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} to quickly access their stats in the Saved Players Page.
        /// </summary>
        public static string SavePlayerText {
            get {
                return ResourceManager.GetString("SavePlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Area.
        /// </summary>
        public static string SecureArea {
            get {
                return ResourceManager.GetString("SecureArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squad.
        /// </summary>
        public static string Squad {
            get {
                return ResourceManager.GetString("Squad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squad Listing.
        /// </summary>
        public static string SquadListing {
            get {
                return ResourceManager.GetString("SquadListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays on {0}.
        /// </summary>
        public static string SquadPlatformText {
            get {
                return ResourceManager.GetString("SquadPlatformText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard User.
        /// </summary>
        public static string StandardUser {
            get {
                return ResourceManager.GetString("StandardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats Comparison (Beta).
        /// </summary>
        public static string StatsComparison {
            get {
                return ResourceManager.GetString("StatsComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suicides.
        /// </summary>
        public static string Suicides {
            get {
                return ResourceManager.GetString("Suicides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Supporter.
        /// </summary>
        public static string Supporter {
            get {
                return ResourceManager.GetString("Supporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist Hunt.
        /// </summary>
        public static string TerroristHunt {
            get {
                return ResourceManager.GetString("TerroristHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Translator.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner of this account has blocked access to view stats..
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified User.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W/L.
        /// </summary>
        public static string WL {
            get {
                return ResourceManager.GetString("WL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year {0}.
        /// </summary>
        public static string YearSelection {
            get {
                return ResourceManager.GetString("YearSelection", resourceCulture);
            }
        }
    }
}
