//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Interface {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DragonFruit.Six.Locale.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        public static string ClearSaved {
            get {
                return ResourceManager.GetString("ClearSaved", resourceCulture);
            }
        }
        
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        public static string DefaultPlatform {
            get {
                return ResourceManager.GetString("DefaultPlatform", resourceCulture);
            }
        }
        
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string PlayerStats {
            get {
                return ResourceManager.GetString("PlayerStats", resourceCulture);
            }
        }
        
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        public static string SavePlayerTip {
            get {
                return ResourceManager.GetString("SavePlayerTip", resourceCulture);
            }
        }
        
        public static string SearchingForAccount {
            get {
                return ResourceManager.GetString("SearchingForAccount", resourceCulture);
            }
        }
        
        public static string SearchOperators {
            get {
                return ResourceManager.GetString("SearchOperators", resourceCulture);
            }
        }
        
        public static string SearchRecents {
            get {
                return ResourceManager.GetString("SearchRecents", resourceCulture);
            }
        }
        
        public static string SeasonChangeTip {
            get {
                return ResourceManager.GetString("SeasonChangeTip", resourceCulture);
            }
        }
        
        public static string ServerSetTheme {
            get {
                return ResourceManager.GetString("ServerSetTheme", resourceCulture);
            }
        }
        
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        public static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        public static string UpdateAssets {
            get {
                return ResourceManager.GetString("UpdateAssets", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string ShareAccountString {
            get {
                return ResourceManager.GetString("ShareAccountString", resourceCulture);
            }
        }
        
        public static string ShareAppString {
            get {
                return ResourceManager.GetString("ShareAppString", resourceCulture);
            }
        }
        
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        public static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }
        
        public static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }
        
        public static string ConfirmSave {
            get {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }
        
        public static string LoadingStats {
            get {
                return ResourceManager.GetString("LoadingStats", resourceCulture);
            }
        }
        
        public static string OperatorStats {
            get {
                return ResourceManager.GetString("OperatorStats", resourceCulture);
            }
        }
        
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        public static string RetryConnection {
            get {
                return ResourceManager.GetString("RetryConnection", resourceCulture);
            }
        }
        
        public static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
        
        public static string SteamNews {
            get {
                return ResourceManager.GetString("SteamNews", resourceCulture);
            }
        }
        
        public static string UserRemoved {
            get {
                return ResourceManager.GetString("UserRemoved", resourceCulture);
            }
        }
        
        public static string UserSaved {
            get {
                return ResourceManager.GetString("UserSaved", resourceCulture);
            }
        }
        
        public static string ViewRecents {
            get {
                return ResourceManager.GetString("ViewRecents", resourceCulture);
            }
        }
        
        public static string WeaponStats {
            get {
                return ResourceManager.GetString("WeaponStats", resourceCulture);
            }
        }
        
        public static string SeasonSelectionTemplate {
            get {
                return ResourceManager.GetString("SeasonSelectionTemplate", resourceCulture);
            }
        }
        
        public static string ShareProfile {
            get {
                return ResourceManager.GetString("ShareProfile", resourceCulture);
            }
        }
        
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        public static string ConfirmClearTitle {
            get {
                return ResourceManager.GetString("ConfirmClearTitle", resourceCulture);
            }
        }
        
        public static string ClearSavedComplete {
            get {
                return ResourceManager.GetString("ClearSavedComplete", resourceCulture);
            }
        }
        
        public static string UpdateAssetsComplete {
            get {
                return ResourceManager.GetString("UpdateAssetsComplete", resourceCulture);
            }
        }
        
        public static string PlayersCleared {
            get {
                return ResourceManager.GetString("PlayersCleared", resourceCulture);
            }
        }
        
        public static string AppLibraries {
            get {
                return ResourceManager.GetString("AppLibraries", resourceCulture);
            }
        }
        
        public static string AppIconSource {
            get {
                return ResourceManager.GetString("AppIconSource", resourceCulture);
            }
        }
        
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        public static string SelectAccount {
            get {
                return ResourceManager.GetString("SelectAccount", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
    }
}
