//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Dragon6.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account.
        /// </summary>
        public static string AccountSelect {
            get {
                return ResourceManager.GetString("AccountSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Icons from various artists (sourced from the noun project).
        /// </summary>
        public static string AppIconSource {
            get {
                return ResourceManager.GetString("AppIconSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Party Libraries.
        /// </summary>
        public static string AppLibraries {
            get {
                return ResourceManager.GetString("AppLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Saved Profiles.
        /// </summary>
        public static string ClearSaved {
            get {
                return ResourceManager.GetString("ClearSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Profiles Cleared.
        /// </summary>
        public static string ClearSavedComplete {
            get {
                return ResourceManager.GetString("ClearSavedComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear saved profiles?.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Clear.
        /// </summary>
        public static string ConfirmClearTitle {
            get {
                return ResourceManager.GetString("ConfirmClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Remove.
        /// </summary>
        public static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Save.
        /// </summary>
        public static string ConfirmSave {
            get {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Platform.
        /// </summary>
        public static string DefaultPlatform {
            get {
                return ResourceManager.GetString("DefaultPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by: {0}.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It.
        /// </summary>
        public static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Stats... ({0}).
        /// </summary>
        public static string LoadingStats {
            get {
                return ResourceManager.GetString("LoadingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Stats.
        /// </summary>
        public static string OperatorStats {
            get {
                return ResourceManager.GetString("OperatorStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Cleared.
        /// </summary>
        public static string PlayersCleared {
            get {
                return ResourceManager.GetString("PlayersCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Stats.
        /// </summary>
        public static string PlayerStats {
            get {
                return ResourceManager.GetString("PlayerStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Players.
        /// </summary>
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} from your home page?.
        /// </summary>
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Connection.
        /// </summary>
        public static string RetryConnection {
            get {
                return ResourceManager.GetString("RetryConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Double tap a player&apos;s card to save them.
        /// </summary>
        public static string SavePlayerTip {
            get {
                return ResourceManager.GetString("SavePlayerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to your home page?.
        /// </summary>
        public static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking up {0} on {1}.
        /// </summary>
        public static string SearchingForAccount {
            get {
                return ResourceManager.GetString("SearchingForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Operators.
        /// </summary>
        public static string SearchOperators {
            get {
                return ResourceManager.GetString("SearchOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Recent Players.
        /// </summary>
        public static string SearchRecents {
            get {
                return ResourceManager.GetString("SearchRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Tap the top card to change seasons.
        /// </summary>
        public static string SeasonChangeTip {
            get {
                return ResourceManager.GetString("SeasonChangeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Season.
        /// </summary>
        public static string SeasonSelect {
            get {
                return ResourceManager.GetString("SeasonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Y{1}S{2}).
        /// </summary>
        public static string SeasonSelectionTemplate {
            get {
                return ResourceManager.GetString("SeasonSelectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server set theme.
        /// </summary>
        public static string ServerSetTheme {
            get {
                return ResourceManager.GetString("ServerSetTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out {0}&apos;s Stats on Dragon6!.
        /// </summary>
        public static string ShareAccountString {
            get {
                return ResourceManager.GetString("ShareAccountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out Dragon6 - a free R6 stats tracker!.
        /// </summary>
        public static string ShareAppString {
            get {
                return ResourceManager.GetString("ShareAppString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Profile.
        /// </summary>
        public static string ShareProfile {
            get {
                return ResourceManager.GetString("ShareProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by: {0}.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by Steam.
        /// </summary>
        public static string SteamNews {
            get {
                return ResourceManager.GetString("SteamNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understood.
        /// </summary>
        public static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        public static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Assets.
        /// </summary>
        public static string UpdateAssets {
            get {
                return ResourceManager.GetString("UpdateAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets Updated.
        /// </summary>
        public static string UpdateAssetsComplete {
            get {
                return ResourceManager.GetString("UpdateAssetsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Removed.
        /// </summary>
        public static string UserRemoved {
            get {
                return ResourceManager.GetString("UserRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Saved.
        /// </summary>
        public static string UserSaved {
            get {
                return ResourceManager.GetString("UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Recents.
        /// </summary>
        public static string ViewRecents {
            get {
                return ResourceManager.GetString("ViewRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Stats.
        /// </summary>
        public static string WeaponStats {
            get {
                return ResourceManager.GetString("WeaponStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
