//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mobile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mobile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Mobile", typeof(Mobile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandons.
        /// </summary>
        public static string Abandon {
            get {
                return ResourceManager.GetString("Abandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned.
        /// </summary>
        public static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Resources.
        /// </summary>
        public static string AboutAppResourcesText {
            get {
                return ResourceManager.GetString("AboutAppResourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Dragon6.
        /// </summary>
        public static string AboutAppText {
            get {
                return ResourceManager.GetString("AboutAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Blocked.
        /// </summary>
        public static string AccessBlocked {
            get {
                return ResourceManager.GetString("AccessBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we can&apos;t show this account due to GDPR rules..
        /// </summary>
        public static string AccessBlockedMessage {
            get {
                return ResourceManager.GetString("AccessBlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string AddMenuHead {
            get {
                return ResourceManager.GetString("AddMenuHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Leaderboard.
        /// </summary>
        public static string AddToLeaderboard {
            get {
                return ResourceManager.GetString("AddToLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Saved Players.
        /// </summary>
        public static string AddToSaved {
            get {
                return ResourceManager.GetString("AddToSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string AnHourAgo {
            get {
                return ResourceManager.GetString("AnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Assets Updated.
        /// </summary>
        public static string AssetsUpdated {
            get {
                return ResourceManager.GetString("AssetsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker.
        /// </summary>
        public static string Attacker {
            get {
                return ResourceManager.GetString("Attacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Score.
        /// </summary>
        public static string BestScore {
            get {
                return ResourceManager.GetString("BestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Scores.
        /// </summary>
        public static string BestScores {
            get {
                return ResourceManager.GetString("BestScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Tester.
        /// </summary>
        public static string BetaTester {
            get {
                return ResourceManager.GetString("BetaTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        public static string BombMode {
            get {
                return ResourceManager.GetString("BombMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t save this profile....
        /// </summary>
        public static string CantSaveProfile {
            get {
                return ResourceManager.GetString("CantSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual.
        /// </summary>
        public static string Casual {
            get {
                return ResourceManager.GetString("Casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual K/D.
        /// </summary>
        public static string CasualKD {
            get {
                return ResourceManager.GetString("CasualKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual W/L.
        /// </summary>
        public static string CasualWL {
            get {
                return ResourceManager.GetString("CasualWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Operators.
        /// </summary>
        public static string ClearOperators {
            get {
                return ResourceManager.GetString("ClearOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear all saved operators?.
        /// </summary>
        public static string ClearOperatorsPrompt {
            get {
                return ResourceManager.GetString("ClearOperatorsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Saved Profiles.
        /// </summary>
        public static string ClearSavedProfiles {
            get {
                return ResourceManager.GetString("ClearSavedProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearSavedProfilesButton {
            get {
                return ResourceManager.GetString("ClearSavedProfilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Feature is Coming Soon....
        /// </summary>
        public static string ComingSoonMessage {
            get {
                return ResourceManager.GetString("ComingSoonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Save.
        /// </summary>
        public static string ConfirmSave {
            get {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Season.
        /// </summary>
        public static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme Disabled. Please restart for changes to become visible..
        /// </summary>
        public static string DarkThemeOff {
            get {
                return ResourceManager.GetString("DarkThemeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme Enabled. Please restart for changes to become visible..
        /// </summary>
        public static string DarkThemeOn {
            get {
                return ResourceManager.GetString("DarkThemeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Database.
        /// </summary>
        public static string DatabaseUpgrade {
            get {
                return ResourceManager.GetString("DatabaseUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dragon6 App has been reset due to a database upgrade. We apologise for any inconvenience.
        /// </summary>
        public static string DatabaseUpgradeBody {
            get {
                return ResourceManager.GetString("DatabaseUpgradeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string Defender {
            get {
                return ResourceManager.GetString("Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downs.
        /// </summary>
        public static string Downs {
            get {
                return ResourceManager.GetString("Downs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBNOs vs Revives.
        /// </summary>
        public static string DownsRevives {
            get {
                return ResourceManager.GetString("DownsRevives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 has been reset. Please restart for changes to take effect..
        /// </summary>
        public static string Dragon6ResetSuccess {
            get {
                return ResourceManager.GetString("Dragon6ResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots Fired.
        /// </summary>
        public static string Fired {
            get {
                return ResourceManager.GetString("Fired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Stats.
        /// </summary>
        public static string GunStats {
            get {
                return ResourceManager.GetString("GunStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshots.
        /// </summary>
        public static string HeadshotsText {
            get {
                return ResourceManager.GetString("HeadshotsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots Hit.
        /// </summary>
        public static string Hit {
            get {
                return ResourceManager.GetString("Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Saved Profiles.
        /// </summary>
        public static string HomeLoading {
            get {
                return ResourceManager.GetString("HomeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostage.
        /// </summary>
        public static string HostageMode {
            get {
                return ResourceManager.GetString("HostageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons From Various Creators downloaded from the Noun Project.
        /// </summary>
        public static string IconsAttribution {
            get {
                return ResourceManager.GetString("IconsAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K/D.
        /// </summary>
        public static string KD {
            get {
                return ResourceManager.GetString("KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Knifes {
            get {
                return ResourceManager.GetString("Knifes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Match.
        /// </summary>
        public static string LastMatch {
            get {
                return ResourceManager.GetString("LastMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen.
        /// </summary>
        public static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string Losses {
            get {
                return ResourceManager.GetString("Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainPageHomeText {
            get {
                return ResourceManager.GetString("MainPageHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string MainPageNewsText {
            get {
                return ResourceManager.GetString("MainPageNewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: To save players, double tap their photo....
        /// </summary>
        public static string MainPageSaveHint {
            get {
                return ResourceManager.GetString("MainPageSaveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Rank.
        /// </summary>
        public static string MaxRank {
            get {
                return ResourceManager.GetString("MaxRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Kills.
        /// </summary>
        public static string MeleeKills {
            get {
                return ResourceManager.GetString("MeleeKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Dragon6.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Recent Players.
        /// </summary>
        public static string MenuRecents {
            get {
                return ResourceManager.GetString("MenuRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Menu.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMR Change.
        /// </summary>
        public static string MMRChange {
            get {
                return ResourceManager.GetString("MMRChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By Steam.
        /// </summary>
        public static string NewsPageSteamAttribute {
            get {
                return ResourceManager.GetString("NewsPageSteamAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Internet connection is required to use Dragon6.
        /// </summary>
        public static string NoInternetErrorText {
            get {
                return ResourceManager.GetString("NoInternetErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Connection.
        /// </summary>
        public static string NoInternetRetryText {
            get {
                return ResourceManager.GetString("NoInternetRetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Kills or Deaths.
        /// </summary>
        public static string NoKD {
            get {
                return ResourceManager.GetString("NoKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Played Yet.
        /// </summary>
        public static string NotPlayed {
            get {
                return ResourceManager.GetString("NotPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of total.
        /// </summary>
        public static string OfTotal {
            get {
                return ResourceManager.GetString("OfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute ago.
        /// </summary>
        public static string OneMinuteAgo {
            get {
                return ResourceManager.GetString("OneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month ago.
        /// </summary>
        public static string OneMonthAgo {
            get {
                return ResourceManager.GetString("OneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second ago.
        /// </summary>
        public static string OneSecondAgo {
            get {
                return ResourceManager.GetString("OneSecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one year ago.
        /// </summary>
        public static string OneYearAgo {
            get {
                return ResourceManager.GetString("OneYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string OperationPrefix {
            get {
                return ResourceManager.GetString("OperationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator {0}.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Ability.
        /// </summary>
        public static string OperatorAction {
            get {
                return ResourceManager.GetString("OperatorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Removed.
        /// </summary>
        public static string OperatorDeleted {
            get {
                return ResourceManager.GetString("OperatorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Headshot %.
        /// </summary>
        public static string OperatorHS {
            get {
                return ResourceManager.GetString("OperatorHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator K/D.
        /// </summary>
        public static string OperatorKD {
            get {
                return ResourceManager.GetString("OperatorKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Kills Per Round.
        /// </summary>
        public static string OperatorKPR {
            get {
                return ResourceManager.GetString("OperatorKPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Saved Successfully.
        /// </summary>
        public static string OperatorSaved {
            get {
                return ResourceManager.GetString("OperatorSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators Cleared.
        /// </summary>
        public static string OperatorsCleared {
            get {
                return ResourceManager.GetString("OperatorsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Operator....
        /// </summary>
        public static string OperatorSearch {
            get {
                return ResourceManager.GetString("OperatorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Stats.
        /// </summary>
        public static string OperatorStats {
            get {
                return ResourceManager.GetString("OperatorStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue getting the operator stats. Please try reloading the stats or try again later..
        /// </summary>
        public static string OperatorStatsError {
            get {
                return ResourceManager.GetString("OperatorStatsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Stats Download Error.
        /// </summary>
        public static string OperatorStatsErrorShort {
            get {
                return ResourceManager.GetString("OperatorStatsErrorShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator W/L.
        /// </summary>
        public static string OperatorWL {
            get {
                return ResourceManager.GetString("OperatorWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall {0}.
        /// </summary>
        public static string Overall {
            get {
                return ResourceManager.GetString("Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall K/D.
        /// </summary>
        public static string OverallKD {
            get {
                return ResourceManager.GetString("OverallKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall W/L.
        /// </summary>
        public static string OverallWL {
            get {
                return ResourceManager.GetString("OverallWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penetration Kills.
        /// </summary>
        public static string PenetrationKills {
            get {
                return ResourceManager.GetString("PenetrationKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Changed to.
        /// </summary>
        public static string PlatformChanged {
            get {
                return ResourceManager.GetString("PlatformChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Platform.
        /// </summary>
        public static string PlatformSelectorText {
            get {
                return ResourceManager.GetString("PlatformSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/Write Error.
        /// </summary>
        public static string PlayerLinkErrorShort {
            get {
                return ResourceManager.GetString("PlayerLinkErrorShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the player&apos;s name and platform.
        /// </summary>
        public static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Not found.
        /// </summary>
        public static string PlayerNotFoundShort {
            get {
                return ResourceManager.GetString("PlayerNotFoundShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and we cannot remove this profile. Please check disk space and/or reset the application.
        /// </summary>
        public static string PlayerRemoveError {
            get {
                return ResourceManager.GetString("PlayerRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Removed.
        /// </summary>
        public static string PlayersRemoved {
            get {
                return ResourceManager.GetString("PlayersRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Six Operator.
        /// </summary>
        public static string R6OperatorText {
            get {
                return ResourceManager.GetString("R6OperatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Difference From.
        /// </summary>
        public static string RankDifference {
            get {
                return ResourceManager.GetString("RankDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked {0}.
        /// </summary>
        public static string Ranked {
            get {
                return ResourceManager.GetString("Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked K/D.
        /// </summary>
        public static string RankedKD {
            get {
                return ResourceManager.GetString("RankedKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Ranked Region.
        /// </summary>
        public static string RankedRegionSelectorText {
            get {
                return ResourceManager.GetString("RankedRegionSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the top card to change seasons.
        /// </summary>
        public static string RankedTip {
            get {
                return ResourceManager.GetString("RankedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked W/L.
        /// </summary>
        public static string RankedWL {
            get {
                return ResourceManager.GetString("RankedWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank(s).
        /// </summary>
        public static string Ranks {
            get {
                return ResourceManager.GetString("Ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Cleared.
        /// </summary>
        public static string RecentsClearedConfirmation {
            get {
                return ResourceManager.GetString("RecentsClearedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Region to.
        /// </summary>
        public static string RegionChanged {
            get {
                return ResourceManager.GetString("RegionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        public static string RemovePlayer {
            get {
                return ResourceManager.GetString("RemovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Dragon6.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revives.
        /// </summary>
        public static string Revives {
            get {
                return ResourceManager.GetString("Revives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum saved players. Please remove some and try again....
        /// </summary>
        public static string SavedPlayersLimit {
            get {
                return ResourceManager.GetString("SavedPlayersLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Reached.
        /// </summary>
        public static string SavedPlayersLimitShort {
            get {
                return ResourceManager.GetString("SavedPlayersLimitShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Operator.
        /// </summary>
        public static string SaveOperator {
            get {
                return ResourceManager.GetString("SaveOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and we cannot save this profile. Please check disk space and/or reset the application.
        /// </summary>
        public static string SavePlayerError {
            get {
                return ResourceManager.GetString("SavePlayerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Player.
        /// </summary>
        public static string SearchPlayerBarText {
            get {
                return ResourceManager.GetString("SearchPlayerBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Recents.
        /// </summary>
        public static string SearchRecents {
            get {
                return ResourceManager.GetString("SearchRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Abandon %.
        /// </summary>
        public static string SeasonAbandon {
            get {
                return ResourceManager.GetString("SeasonAbandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal.
        /// </summary>
        public static string Seasonal {
            get {
                return ResourceManager.GetString("Seasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the top card to change seasons.
        /// </summary>
        public static string SeasonChangeTip {
            get {
                return ResourceManager.GetString("SeasonChangeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season K/D.
        /// </summary>
        public static string SeasonKD {
            get {
                return ResourceManager.GetString("SeasonKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Season.
        /// </summary>
        public static string SeasonSelector {
            get {
                return ResourceManager.GetString("SeasonSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season W/L.
        /// </summary>
        public static string SeasonWL {
            get {
                return ResourceManager.GetString("SeasonWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Area.
        /// </summary>
        public static string SecureAreaMode {
            get {
                return ResourceManager.GetString("SecureAreaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Maintenance.
        /// </summary>
        public static string ServerInMaintenance {
            get {
                return ResourceManager.GetString("ServerInMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Servers Online.
        /// </summary>
        public static string ServersOnline {
            get {
                return ResourceManager.GetString("ServersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status.
        /// </summary>
        public static string ServerStatus {
            get {
                return ResourceManager.GetString("ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Dragon6.
        /// </summary>
        public static string ShareApp {
            get {
                return ResourceManager.GetString("ShareApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out Dragon6, a free Rainbow Six Siege Stat Tracker.
        /// </summary>
        public static string ShareAppText {
            get {
                return ResourceManager.GetString("ShareAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Profile.
        /// </summary>
        public static string ShareProfile {
            get {
                return ResourceManager.GetString("ShareProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out {0} on Dragon6 - A Free Rainbow Six Stat Tracker.
        /// </summary>
        public static string ShareProfileContent {
            get {
                return ResourceManager.GetString("ShareProfileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific.
        /// </summary>
        public static string Specific {
            get {
                return ResourceManager.GetString("Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string StatsGeneral {
            get {
                return ResourceManager.GetString("StatsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Stats.
        /// </summary>
        public static string StatsHeader {
            get {
                return ResourceManager.GetString("StatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Stats... ({0}).
        /// </summary>
        public static string StatsLoadingBar {
            get {
                return ResourceManager.GetString("StatsLoadingBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string StatsOperator {
            get {
                return ResourceManager.GetString("StatsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        public static string StatsRanked {
            get {
                return ResourceManager.GetString("StatsRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suicides.
        /// </summary>
        public static string Suicides {
            get {
                return ResourceManager.GetString("Suicides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Supporter.
        /// </summary>
        public static string Supporter {
            get {
                return ResourceManager.GetString("Supporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server-Set Theme.
        /// </summary>
        public static string ThemeEnforced {
            get {
                return ResourceManager.GetString("ThemeEnforced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist Hunt.
        /// </summary>
        public static string THunt {
            get {
                return ResourceManager.GetString("THunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist Hunt K/D.
        /// </summary>
        public static string THuntKD {
            get {
                return ResourceManager.GetString("THuntKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist Hunt W/L.
        /// </summary>
        public static string THuntWL {
            get {
                return ResourceManager.GetString("THuntWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Played.
        /// </summary>
        public static string TimePlayed {
            get {
                return ResourceManager.GetString("TimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Dragon6.
        /// </summary>
        public static string TranslateApp {
            get {
                return ResourceManager.GetString("TranslateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon6 Translator.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers in Mainatainance.
        /// </summary>
        public static string UbiServersOffline {
            get {
                return ResourceManager.GetString("UbiServersOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncertainty.
        /// </summary>
        public static string Uncertainty {
            get {
                return ResourceManager.GetString("Uncertainty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It.
        /// </summary>
        public static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occoured\nThe Dragon6 Team have been woken up and will work to fix this as fast as possible.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Season-Based Info.
        /// </summary>
        public static string UpdateAssets {
            get {
                return ResourceManager.GetString("UpdateAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateAssetsButton {
            get {
                return ResourceManager.GetString("UpdateAssetsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified User.
        /// </summary>
        public static string VerifiedUser {
            get {
                return ResourceManager.GetString("VerifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault Rifle.
        /// </summary>
        public static string WeaponAssault {
            get {
                return ResourceManager.GetString("WeaponAssault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Six Weapon Class.
        /// </summary>
        public static string WeaponClass {
            get {
                return ResourceManager.GetString("WeaponClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksman Rifle.
        /// </summary>
        public static string WeaponDMR {
            get {
                return ResourceManager.GetString("WeaponDMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMG.
        /// </summary>
        public static string WeaponLMG {
            get {
                return ResourceManager.GetString("WeaponLMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Pistol.
        /// </summary>
        public static string WeaponMachinePistol {
            get {
                return ResourceManager.GetString("WeaponMachinePistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Not Found.
        /// </summary>
        public static string WeaponNotFound {
            get {
                return ResourceManager.GetString("WeaponNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has happened and we cannot find this class. Try another one or give it some time and check later..
        /// </summary>
        public static string WeaponNotFoundMessage {
            get {
                return ResourceManager.GetString("WeaponNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handgun.
        /// </summary>
        public static string WeaponPistol {
            get {
                return ResourceManager.GetString("WeaponPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun.
        /// </summary>
        public static string WeaponShotgun {
            get {
                return ResourceManager.GetString("WeaponShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string WeaponSMG {
            get {
                return ResourceManager.GetString("WeaponSMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W/L.
        /// </summary>
        public static string WL {
            get {
                return ResourceManager.GetString("WL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string Won {
            get {
                return ResourceManager.GetString("Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
