//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ranks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ranks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Ranks", typeof(Ranks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze 1.
        /// </summary>
        internal static string Bronze1 {
            get {
                return ResourceManager.GetString("Bronze1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze 2.
        /// </summary>
        internal static string Bronze2 {
            get {
                return ResourceManager.GetString("Bronze2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze 3.
        /// </summary>
        internal static string Bronze3 {
            get {
                return ResourceManager.GetString("Bronze3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze 4.
        /// </summary>
        internal static string Bronze4 {
            get {
                return ResourceManager.GetString("Bronze4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze5.
        /// </summary>
        internal static string Bronze5 {
            get {
                return ResourceManager.GetString("Bronze5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champion.
        /// </summary>
        internal static string Champion {
            get {
                return ResourceManager.GetString("Champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper 1.
        /// </summary>
        internal static string Copper1 {
            get {
                return ResourceManager.GetString("Copper1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper 2.
        /// </summary>
        internal static string Copper2 {
            get {
                return ResourceManager.GetString("Copper2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper 3.
        /// </summary>
        internal static string Copper3 {
            get {
                return ResourceManager.GetString("Copper3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper 4.
        /// </summary>
        internal static string Copper4 {
            get {
                return ResourceManager.GetString("Copper4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper 5.
        /// </summary>
        internal static string Copper5 {
            get {
                return ResourceManager.GetString("Copper5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        internal static string Diamond {
            get {
                return ResourceManager.GetString("Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold 1.
        /// </summary>
        internal static string Gold1 {
            get {
                return ResourceManager.GetString("Gold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold 2.
        /// </summary>
        internal static string Gold2 {
            get {
                return ResourceManager.GetString("Gold2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold 3.
        /// </summary>
        internal static string Gold3 {
            get {
                return ResourceManager.GetString("Gold3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold 4.
        /// </summary>
        internal static string Gold4 {
            get {
                return ResourceManager.GetString("Gold4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum 1.
        /// </summary>
        internal static string Plat1 {
            get {
                return ResourceManager.GetString("Plat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum 2.
        /// </summary>
        internal static string Plat2 {
            get {
                return ResourceManager.GetString("Plat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum 3.
        /// </summary>
        internal static string Plat3 {
            get {
                return ResourceManager.GetString("Plat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver 1.
        /// </summary>
        internal static string Silver1 {
            get {
                return ResourceManager.GetString("Silver1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver 2.
        /// </summary>
        internal static string Silver2 {
            get {
                return ResourceManager.GetString("Silver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver 3.
        /// </summary>
        internal static string Silver3 {
            get {
                return ResourceManager.GetString("Silver3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver 4.
        /// </summary>
        internal static string Silver4 {
            get {
                return ResourceManager.GetString("Silver4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver 5.
        /// </summary>
        internal static string Silver5 {
            get {
                return ResourceManager.GetString("Silver5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrakned.
        /// </summary>
        internal static string Unranked {
            get {
                return ResourceManager.GetString("Unranked", resourceCulture);
            }
        }
    }
}
