//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFruit.Six.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Terminology {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Terminology() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonFruit.Six.Locale.Terminology", typeof(Terminology).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned.
        /// </summary>
        public static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandons.
        /// </summary>
        public static string Abandons {
            get {
                return ResourceManager.GetString("Abandons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assists.
        /// </summary>
        public static string Assists {
            get {
                return ResourceManager.GetString("Assists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker.
        /// </summary>
        public static string Attacker {
            get {
                return ResourceManager.GetString("Attacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attackers.
        /// </summary>
        public static string Attackers {
            get {
                return ResourceManager.GetString("Attackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATK.
        /// </summary>
        public static string AttackerShort {
            get {
                return ResourceManager.GetString("AttackerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        public static string Bomb {
            get {
                return ResourceManager.GetString("Bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual.
        /// </summary>
        public static string Casual {
            get {
                return ResourceManager.GetString("Casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Season.
        /// </summary>
        public static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Deaths.
        /// </summary>
        public static string DeathsCount {
            get {
                return ResourceManager.GetString("DeathsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string Defender {
            get {
                return ResourceManager.GetString("Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenders.
        /// </summary>
        public static string Defenders {
            get {
                return ResourceManager.GetString("Defenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEF.
        /// </summary>
        public static string DefenderShort {
            get {
                return ResourceManager.GetString("DefenderShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downs.
        /// </summary>
        public static string Downs {
            get {
                return ResourceManager.GetString("Downs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Downs.
        /// </summary>
        public static string DownsCount {
            get {
                return ResourceManager.GetString("DownsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshots.
        /// </summary>
        public static string Headshots {
            get {
                return ResourceManager.GetString("Headshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscores.
        /// </summary>
        public static string Highscores {
            get {
                return ResourceManager.GetString("Highscores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostage.
        /// </summary>
        public static string Hostage {
            get {
                return ResourceManager.GetString("Hostage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K/D.
        /// </summary>
        public static string KD {
            get {
                return ResourceManager.GetString("KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Match.
        /// </summary>
        public static string LastMatch {
            get {
                return ResourceManager.GetString("LastMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Losses.
        /// </summary>
        public static string Losses {
            get {
                return ResourceManager.GetString("Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Melee {
            get {
                return ResourceManager.GetString("Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string Overall {
            get {
                return ResourceManager.GetString("Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penetrations.
        /// </summary>
        public static string Penetrations {
            get {
                return ResourceManager.GetString("Penetrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        public static string Ranked {
            get {
                return ResourceManager.GetString("Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revives.
        /// </summary>
        public static string Revives {
            get {
                return ResourceManager.GetString("Revives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Revives.
        /// </summary>
        public static string RevivesCount {
            get {
                return ResourceManager.GetString("RevivesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal.
        /// </summary>
        public static string Seasonal {
            get {
                return ResourceManager.GetString("Seasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Area.
        /// </summary>
        public static string Secure {
            get {
                return ResourceManager.GetString("Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suicides.
        /// </summary>
        public static string Suicides {
            get {
                return ResourceManager.GetString("Suicides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist Hunt.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unranked.
        /// </summary>
        public static string Unranked {
            get {
                return ResourceManager.GetString("Unranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        public static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} Wins.
        /// </summary>
        public static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} W/L.
        /// </summary>
        public static string WL {
            get {
                return ResourceManager.GetString("WL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W/L.
        /// </summary>
        public static string WLName {
            get {
                return ResourceManager.GetString("WLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string Won {
            get {
                return ResourceManager.GetString("Won", resourceCulture);
            }
        }
    }
}
